language: ruby
cache: bundler

rvm:
  - 2.2.6
  - 2.3.1
  - 2.4.0

services:
  - postgresql

before_script:
  - psql -c 'create database rails_admin_json_translate_test;' -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rails test
