language: ruby
dist: trusty

addons:
  postgresql: 9.6

services:
  - postgresql

rvm:
  - 2.2.6
  - 2.3.1
  - 2.4.0

before_script:
  - psql -c 'create database rails_admin_json_translate_test;' -U postgres
  - cd test/dummy && bundle exec rails db:migrate

script:
  - bundle exec rails test

cache: bundler
